{{- define "containers/workdir" }}
{{- if .Values.workdir.cm.data }}
- name: workdir-code
  image: docker.io/alpine:3
  volumeMounts:
    {{ include "workdir/volumeMount" . | indent 4 }}
  env:
    - name: LUNCHPAIL_SUBDIR
      value: {{ .Values.workdir.cm.mount_path | default "" }}
  command:
    - /bin/sh
    - "-c"
    - |
      mkdir -p /workdir/$LUNCHPAIL_SUBDIR
      cp -aH /workdir-code/* /workdir/$LUNCHPAIL_SUBDIR
      find /workdir
{{- end }}
{{- end }}
