apiVersion: v1
name: codeflare-third-party
description: Deploys CodeFlare third-party dependencies
type: application

# Chart version.
version: 0.0.1

# CodeFlare version.
appVersion: "latest"

dependencies:
- name: kuberay-operator
  version: 0.5.0
  repository: https://ray-project.github.io/kuberay-helm/

- name: fluent-bit
  version: 0.30.4
  repository: https://fluent.github.io/helm-charts

- name: kube-fledged
  version: 0.10.0
  repository: https://senthilrch.github.io/kubefledged-charts
