apiVersion: codeflare.dev/v1alpha1
kind: Application
metadata:
  name: hap
  namespace: {{ .Values.namespace.user }}
spec:
  api: ray
  image: ghcr.io/lunchpail/ray22:0.3.0
#  repo: https://github.ibm.com/tmhoangt/foundation-model-stack/tree/RHODS_pipeline/src/llm/rhods/python/ods-automated-hap
  repo: https://github.ibm.com/nickm/foundation-model-stack-1/tree/hap-mem/src/llm/rhods/python/ods-automated-hap
  command: python3 hap_driver.py --input_folder=/mnt/datasets/hapxs --models_folder=/mnt/datasets/hap-models
  supportsGpu: true
  description: >-
    Eliminate Hate and Profanity from a given input data set (parquet
    files) using a given pre-trained model.
  inputs:
    - useas: mount
      sizes:
        xs: hapxs
    - useas: mount
      sizes:
        xs: hap-models
