apiVersion: v1
kind: Secret
metadata:
  name: {{ print .Release.Name "-rclone-config" }}
  namespace: {{ .Release.Namespace }}
  ownerReferences:
    {{ include "owner" . | indent 4 }}
type: Opaque
stringData:
  rclone.conf: |
    [s3]
    type = s3
    acl = public-read
    provider = Other
    env_auth = false
    endpoint = {{ .Values.s3Endpoint }}
    access_key_id = {{ .Values.s3AccessKey }}
    secret_access_key = {{ .Values.s3SecretKey }}

{{- define "rclone/volume" }}
- name: rclone-config
  secret:
    secretName: {{ print .Release.Name "-rclone-config" }}
{{- end }}

{{- define "rclone/volumeMount" }}
- name: rclone-config
  readOnly: true
  mountPath: "/tmp"
{{- end }}
