{{- define "containers/watcher" }}
- name: watcher
  image: {{ print .Values.watcher.image.registry "/" .Values.watcher.image.repo "/lunchpail:" .Values.watcher.image.version }}
  volumeMounts:
    {{ include "workdir/volumeMount" . | indent 4 }}
  command:
    - /bin/sh
    - -c
    - |
      cp /usr/local/bin/lunchpail /workdir/lunchpail
{{- end }}
