{{- define "containers/controller" }}
- name: controller
  livenessProbe:
    initialDelaySeconds: 2
    periodSeconds: 60
    timeoutSeconds: 1
    httpGet:
      path: /healthz
      port: 8080
  readinessProbe:
    initialDelaySeconds: 2
    failureThreshold: 50
    periodSeconds: 2
    timeoutSeconds: 1
    httpGet:
      path: /healthz
      port: 8080
  env:
    {{- include "env" . | indent 4 }}
  volumeMounts:
    {{- include "rclone.volumeMount" . | indent 4 }}

  image: {{ print .Values.global.image.registry "/" .Values.global.image.repo "/jaas-run-controller-lite:" .Chart.AppVersion }}
{{- end }}
