{{- define "containers/controller" }}
- name: controller
  livenessProbe:
    periodSeconds: 60
    timeoutSeconds: 10
    httpGet:
      path: /healthz
      port: 8080
  readinessProbe:
    periodSeconds: 60
    timeoutSeconds: 10
    httpGet:
      path: /healthz
      port: 8080
  env:
    {{- include "env" . | indent 4 }}
  volumeMounts:
    {{- include "rclone.volumeMount" . | indent 4 }}

  image: {{ print .Values.global.image.registry "/" .Values.global.image.repo "/jaas-run-controller-lite:" .Chart.AppVersion }}
{{- end }}
