# The point of this is to give an easy way to debug issues with the in-cluster s3.
# TODO: this should probably only be deployed when in debug mode?
apiVersion: v1
kind: Pod
metadata:
  name: {{ print .Values.name "-client" }}
  namespace: codeflare-system
  labels:
    app.kubernetes.io/part-of: codeflare.dev
    app.kubernetes.io/component: s3
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 0

  containers:
  - name: client
    image: {{ .Values.images.client }}
    imagePullPolicy: IfNotPresent
    envFrom:
      - configMapRef:
          name: {{ .Values.name }}
      - secretRef:
          name: {{ .Values.name }}
    command:
      - sh
      - "-c"
      - |
        until mc alias set s3 $S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY; do
          echo 'Waiting for minio to come alive'
          sleep 1
        done
        sleep infinity
