apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: codeflare-system
  labels:
      app.kubernetes.io/part-of: codeflare.dev
      app.kubernetes.io/component: s3
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.global.s3AccessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.s3SecretKey | b64enc }}
