apiVersion: v1
kind: Secret
metadata:
  name: queuedemo1-cfsecret # avoid dashes for now: https://github.com/datashim-io/datashim/issues/285
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  accessKeyID: {{ .Values.global.s3AccessKey | b64enc }}
  secretAccessKey: {{ .Values.global.s3SecretKey | b64enc }}
