language: go

go:
- 1.22.x

env:
  - ARGS="-e 'test(7.*|8)'" LPA_ARGS="--workdir-via-mount" # mounted workdir tests
  - ARGS="-i 'test7.*' -e 'test7g'"                        # including only test7* tests, excluding test7g and test8 (as they NEEDS_CSI_S3)
  - ARGS="-i 'test(7g|8)'" LPC_ARGS="--s3-mounts"          # only test7g and test8 which need a mounted s3

before_install: ./tests/bin/travis/setup.sh
script: bash -c "./tests/bin/${SCRIPT:-ci.sh} $ARGS"
after_script: if [[ -f /tmp/gpu-config.json ]]; then ./hack/ibmcloud/delete_vm.sh "$(cat /tmp/gpu-config.json)"; fi
