language: bash

services:
  - xvfb

env:
  - ARGS="-e 'test7.*'" NEEDS_CSI_S3=true # full mode, excluding test7*
  - ARGS="-i 'test7.*'" NEEDS_CSI_S3=true # full mode, including only test7*
  - ARGS="-l -i 'test7.*' -e 'test(7g|8)'"     # lite, including only test7* tests, excluding test7g and test8 (as they NEEDS_CSI_S3)
  - ARGS="-l 'test(7g|8)'" NEEDS_CSI_S3=true    # lite, only test7g and test8 which need a mounted s3
  - SCRIPT=dashboard.sh

before_install: ./hack/travis/setup.sh
script: bash -c "./tests/bin/${SCRIPT:-test.sh} $ARGS"
after_script: if [[ -f /tmp/gpu-config.json ]]; then ./hack/ibmcloud/delete_vm.sh "$(cat /tmp/gpu-config.json)"; fi
