language: go

go:
- 1.22.x

env:
  - ARGS="-e 'test(7.*|8)'" # baseline tests
  - ARGS="-i 'test(7.*|8)'" # including only test7* tests (main workqueue tests)
  - SCRIPT=go.sh            # runs all go tests

before_install: ./tests/bin/travis/setup.sh
script: bash -c "./tests/bin/${SCRIPT:-ci.sh} $ARGS"
after_script: if [[ -f /tmp/gpu-config.json ]]; then ./hack/ibmcloud/delete_vm.sh "$(cat /tmp/gpu-config.json)"; fi
