apiVersion: v1
name: jaas-platform
description: Deploys JaaS Platform
type: application

# Chart version.
version: 0.0.1

# Platform version.
appVersion: 0.12.3

dependencies:
# - name: gpu-operator
#   version: 23.3.2
#   repository: https://nvidia.github.io/gpu-operator
#   condition: nvidia.enabled
#   tags:
#     - gpu

- name: jaas-core
  version: 0.0.1
  repository: file://./core
  condition: core.enabled
  tags:
    - core

- name: jaas-s3
  version: 0.0.1
  repository: file://./s3
  condition: core.enabled
  tags:
    - core

- name: dlf-chart
  version: 0.1.0
  repository: file://./datashim
  condition: core.enabled
  tags:
    - core
