apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeflare-run-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: run-controller
    app.kubernetes.io/part-of: codeflare.dev
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: run-controller
      app.kubernetes.io/part-of: codeflare.dev
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: run-controller
        app.kubernetes.io/part-of: codeflare.dev
        app.kubernetes.io/component: controller
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: codeflare-run-controller-account
      volumes:
        {{- include "volume.workdir.nfs" . | indent 8 }}
      containers:
      - name: controller

        {{ if .Values.global.lite }}
        image: {{ print .Values.global.image.registry "/" .Values.global.image.repo "/jaas-run-controller-lite:" .Values.global.image.version }}
        {{ else }}
        image: {{ print .Values.global.image.registry "/" .Values.global.image.repo "/jaas-run-controller:" .Values.global.image.version }}
        {{ end }}

        env:
          - name: IMAGE_REGISTRY
            value: {{ .Values.global.image.registry }}
          - name: IMAGE_REPO
            value: {{ .Values.global.image.repo }}
          - name: IMAGE_VERSION
            value: {{ .Values.global.image.version }}
          - name: CONTROL_PLANE_CONTEXT
            value: {{ .Values.global.jaas.context.name }}
          - name: WORKDIR
            value: /workdir
          - name: WORKDIR_PVC
            value: workdir
          - name: WORKDIR_SERVER
            value: {{ .Values.workdir.clusterIP }}
          - name: DOCKER_HOST
            value: {{ .Values.global.dockerHost | default "host.docker.internal" }}
          - name: INTERNAL_S3_ENDPOINT
            value: {{ .Values.global.s3Endpoint }}
          - name: INTERNAL_S3_ACCESSKEY
            value: {{ .Values.global.s3AccessKey }}
          - name: INTERNAL_S3_SECRETKEY
            value: {{ .Values.global.s3SecretKey }}
        volumeMounts:
        - name: workdir
          mountPath: /workdir
