---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: run-controller
  namespace: {{ .Release.Namespace }}

{{- if .Values.global.jaas.ips }}
imagePullSecrets:
  - name: {{ .Values.global.jaas.ips }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: run-controller
rules:
  # from former application controller
  - apiGroups: [codeflare.dev]
    resources: [applications,applications/status,platformreposecrets,platformreposecrets/status]
    verbs: [list, watch, patch, get]
  - apiGroups: [com.ie.ibm.hpsys]
    resources: [datasets,datasets/status]
    verbs: [list, watch, patch, get]
  
  - apiGroups: [mcad.ibm.com]
    resources: [appwrappers]
    verbs: [watch]

  - apiGroups: [""]
    resources: [secrets]
    verbs: [get,create] # create needed by workqueue/ helm template

  - apiGroups: [""]
    resources: [configmaps,services]
    verbs: [get,create,list]

  # to find the torchx head pod
  - apiGroups: [""]
    resources: [pods,pods/log]
    verbs: [get, create, list, delete, watch, patch]

  - apiGroups: [""]
    resources: [pods/status]
    verbs: [get,patch]

  - apiGroups: [""]
    resources: [pods/log]
    verbs: [get, watch]

  - apiGroups: [rbac.authorization.k8s.io]
    resources: [rolebindings,roles]
    verbs: [get,create,delete]
  - apiGroups: [""]
    resources: [serviceaccounts]
    verbs: [get,create,delete]
    
  - apiGroups: [""]
    resources: [events]
    verbs: [create, list, watch, patch]

  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [create, delete]

  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get,create,delete]

  - apiGroups: [ray.io]
    resources: [rayclusters,rayjobs]
    verbs: [list,get,create,delete]

  - apiGroups: [com.ie.ibm.hpsys]
    resources: [datasets]
    verbs: [get, patch, create, list] # create needed by workqueue/ helm template; list needed by track_workstealer_logs->find_queue_for_run

  - apiGroups: [codeflare.dev]
    resources: [platformreposecrets,platformimagepullsecrets,runsizeconfigurations]
    verbs: [list]
  - apiGroups: [codeflare.dev]
    resources: [runs/status, workerpools/status, workdispatchers/status]
    verbs: [list, watch, patch, get]
  - apiGroups: [codeflare.dev]
    resources: [applications, queues, runs, workerpools, workdispatchers]
    verbs: [create, list, watch, patch, get]
    
  - apiGroups: [mcad.ibm.com]
    resources: [appwrappers]
    verbs: [create, list, get, delete, patch]

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [kopf.dev]
    resources: [kopfexamples]
    verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: run-controller
  namespace: {{ .Release.Namespace }}
rules:

  - apiGroups: [""]
    resources: [secrets]
    verbs: [get,create]

  - apiGroups: [""]
    resources: [persistentvolumeclaims, events]
    verbs: [create]
    
  - apiGroups: [codeflare.dev]
    resources: [runs, runs/status, applications]
    verbs: [list, watch, patch, get]
    
  - apiGroups: [mcad.ibm.com]
    resources: [appwrappers]
    verbs: [create, list, get, delete, patch]

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [kopf.dev]
    resources: [kopfexamples]
    verbs: [list, watch, patch]

  # Application: other resources it produces and manipulates.
  # Here, we create Jobs+PVCs+Pods, but we do not patch/update/delete them ever.
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [create]
  - apiGroups: [""]
    resources: [pods, persistentvolumeclaims]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: run-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: run-controller
subjects:
  - kind: ServiceAccount
    name: run-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: run-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: run-controller
subjects:
  - kind: ServiceAccount
    name: run-controller
