{{- if and (.Values.global.rbac.runAsRoot) (eq .Values.global.type "oc")}}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: jaas-run-controller
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
priority: 0
allowedCapabilities:
  - '*'
allowedUnsafeSysctls:
  - '*'
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - '*'
supplementalGroups:
  type: RunAsAny
volumes:
- '*'
users:
- system:serviceaccount:{{ .Release.Namespace }}:run-controller-account
{{- end }}
