{{- define "containers/minio" }}
- name: minio
  image: docker.io/minio/minio:RELEASE.2024-07-04T14-25-45Z
  command:
    - minio
    - server
    - ./data
  envFrom:
    - secretRef:
        name: {{ print (.Release.Name | trunc 40) "-lunchpail-minio" }}
  ports:
    - containerPort: 9000
{{- end }}
