{{if eq .Values.global.type "oc"}}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: dlf-sidecars-scc
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
priority: 0
allowedCapabilities:
  - '*'
allowedUnsafeSysctls:
  - '*'
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - '*'
supplementalGroups:
  type: RunAsAny
volumes:
  - '*'
users:
  # A user needs to be added for each rook service account.
  # This assumes running in the default sample "rook-ceph" namespace.
  # If other namespaces or service accounts are configured, they need to be updated here.
  - system:serviceaccount:{{ .Release.Namespace }}:csi-provisioner
  - system:serviceaccount:{{ .Release.Namespace }}:csi-nodeplugin
  - system:serviceaccount:{{ .Release.Namespace }}:csi-attacher
  - system:serviceaccount:{{ .Release.Namespace }}:csi-s3
{{ end }}