{{- if .Values.mcad.enabled }}
apiVersion: mcad.ibm.com/v1beta1
kind: AppWrapper
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: shell
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/managed-by: lunchpail.io
  ownerReferences:
    {{ include "owner" . | indent 4 }}
spec:
  resources:
    Items: []
    GenericItems:
      - replicas: 1
        generictemplate:
          {{ include "pod" . | indent 10 }}
{{- else }}
{{ include "pod" . }}
{{- end }}
