name: codeflare-s3

emptyDir:
  sizeLimit: 1Gi

global:
  s3AccessKey: xxx
  s3SecretKey: yyy
  buckets:
    test: zzz

images:
  server: bitnami/minio:2023.8.29
  client: bitnami/minio-client:2023.8.29
