{{- define "queue/env" }}
- name: WORKQUEUE
  value: /queue
- name: POOL
  value: {{ print .Release.Name | trunc 53 }} # workerpool name
- name: RUN_NAME
  value: {{ .Values.runName }} # name of run in which this pool participates
{{- end }}

{{- define "queue/env/dataset" }}
- name: S3_ENDPOINT_VAR
  value: lunchpail_queue_endpoint
- name: AWS_ACCESS_KEY_ID_VAR
  value: lunchpail_queue_accessKeyID
- name: AWS_SECRET_ACCESS_KEY_VAR
  value: lunchpail_queue_secretAccessKey
- name: TASKQUEUE_VAR
  value: lunchpail_queue_bucket
- name: LUNCHPAIL
  value: {{ .Values.lunchpail }}
{{- end }}

{{- define "queue/volumeMount" }}
- mountPath: /queue
  name: queue
{{- end }}

{{- define "queue/volume" }}
- name: queue
  emptyDir: {}
{{- end }}
