{{- define "queue/env" }}
- name: LUNCHPAIL_LOCAL_QUEUE_ROOT
  value: /queue
{{- end }}

{{- define "queue/env/dataset" }}
- name: LUNCHPAIL_QUEUE_PATH
  value: {{ .Values.taskqueue.prefixPath }}
{{- end }}

{{- define "queue/volumeMount" }}
- mountPath: /queue
  name: queue
{{- end }}

{{- define "queue/volume" }}
- name: queue
  emptyDir: {}
{{- end }}
