# watcher script from configmap: volume
{{- define "watcher/volume" }}
- name: watcher
  configMap:
    name: {{ print (.Release.Name | trunc 45) "-watcher" | trunc 53 | trimSuffix "-" }}
    defaultMode: 0755
{{- if .Values.DISABLED }}
- name: sysctl
  configMap:
    name: {{ print (.Release.Name | trunc 46) "-sysctl" }}
    defaultMode: 0755
{{- end }}
{{- end }}

# watcher script from configmap: volumeMount
{{- define "watcher/volumeMount" }}
- name: watcher
  mountPath: "/opt/lunchpail/bin"
{{- if .Values.DISABLED }}
- name: sysctl
  mountPath: "/etc/sysctl.d/lunchpail.conf"
{{- end }}
{{- end }}
