apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: application-controller
    app.kubernetes.io/part-of: codeflare.dev
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: application-controller
      app.kubernetes.io/part-of: codeflare.dev
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: application-controller
        app.kubernetes.io/part-of: codeflare.dev
        app.kubernetes.io/component: controller
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: application-controller-account

      {{- if .Values.global.jaas.ips }}
      imagePullSecrets:
        - {{ .Values.global.jaas.ips }}
      {{- end }}

      containers:
      - name: controller

        {{ if .Values.global.lite }}
        image: {{ print .Values.global.image.registry "/" .Values.global.image.repo "/jaas-application-controller-lite:" .Values.global.image.version  }}
        {{ else }}
        image: {{ print .Values.global.image.registry "/" .Values.global.image.repo "/jaas-application-controller:" .Values.global.image.version }}
        {{ end }}
