FROM ghcr.io/project-codeflare/kopf:0.0.3

# install rclone
RUN apk update && apk add --no-cache rclone

RUN adduser -u 2000 lunchpail -G root --disabled-password && echo "lunchpail:lunchpail" | chpasswd && chmod -R g=u /home/lunchpail
USER lunchpail
ENV HOME=/home/lunchpail
WORKDIR /home/lunchpail

ADD src /src
CMD kopf run /src/handlers.py --verbose
