apiVersion: codeflare.dev/v1alpha1
kind: Application
metadata:
  name: example-ray-qiskit
  namespace: {{ .Values.namespace.examples }}
spec:
  api: ray
  image: ghcr.io/project-codeflare/ray22:0.0.1
  repo: https://github.ibm.com/cloud-computer/codeflare-platform/tree/main/watsonx_ai/charts/applications/templates/examples/ray
  command: python3 main.py
  supportsGpu: false
  requirements:
    - qiskit==0.37.0
