apiVersion: v1
name: codeflare-core
description: Deploys CodeFlare server-side operators and types
type: application

# Chart version.
version: 0.0.1

# CodeFlare version.
appVersion: "latest"

dependencies:
- name: kuberay-operator
  version: 0.5.0
  repository: https://ray-project.github.io/kuberay-helm/
