apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: applications.lunchpail.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: lunchpail.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        # enables the status subresource
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              oneOf:
                - required: [api,image,command,repo] # code via github
                - required: [api,image,command,code] # code via lieral
              properties:
                api:
                  type: string
                  enum:
                    - shell
                    - ray
                    - torch
                    - workqueue

                # if one or more code is provided via literal
                code:
                  type: array
                  items:
                    type: object
                    required: [name,source]
                    properties:
                      name:
                        type: string
                      source:
                        type: string

                # for api=workqueue
                role:
                  type: string
                  enum: [dispatcher,worker]

                image:
                  type: string
                repo:
                  type: string
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                env:
                  type: object
                  additionalProperties:
                    type: string
                requirements:
                  type: array
                  items:
                    type: string
                command:
                  type: string
                minSize:
                  type: string
                  enum: [xxs,xs,sm,md,lg,xl,xxl,auto]
                supportsGpu:
                  type: boolean
                  default: false

                expose:
                  description: |
                    Expose service on given ports
                  type: array
                  items:
                    type: integer

                securityContext:
                  description: |
                    The required container securityContext
                  type: object
                  properties:
                    runAsUser:
                      type: integer
                    runAsGroup:
                      type: integer
                    fsGroup:
                      type: integer
                containerSecurityContext:
                  type: object
                  properties:
                    runAsUser:
                      type: integer
                    runAsGroup:
                      type: integer
                    seLinuxOptions:
                      type: object
                      properties:
                        type:
                          type: string
                        level:
                          type: string

                datasets:
                  type: array
                  items:
                    type: object
                    oneOf:
                      - required: [name,s3]
                      - required: [name,nfs]
                      - required: [name,pvc]
                    properties:
                      name:
                        type: string
                      mountPath:
                        type: string
                      s3:
                        type: object
                        required: [secret,prefix]
                        properties:
                          secret:
                            type: string
                          envPrefix:
                            type: string
                      nfs:
                        type: object
                        required: [server,path]
                        properties:
                          server:
                            type: string
                          path:
                            type: string
                      pvc:
                        type: object
                        required: [claimName]
                        properties:
                          claimName:
                            type: string

            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Queued
                    - Running
                    - Completed
                    - Failed
                    
      additionalPrinterColumns:
        - name: API
          type: string
          description: The distributed API this application uses
          jsonPath: .spec.api
        - name: Command
          type: string
          description: The command line prefix used to run this application
          jsonPath: .spec.command
          priority: 1 # -o wide only
        - name: GPUs?
          type: boolean
          description: Do the workers in this pool support GPU jobs?
          jsonPath: .spec.supportsGpu
        - name: Image
          type: string
          description: The base image this application uses
          jsonPath: .spec.image
        - name: Repo
          type: string
          description: The source repository for this application
          jsonPath: .spec.repo
          priority: 1 # -o wide only
        - name: Description
          type: string
          description: Brief description of this Application
          jsonPath: .spec.description
          priority: 1 # -o wide only
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: applications
    # singular name to be used as an alias on the CLI and for display
    singular: application
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Application
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - app
