package status

import (
	"fmt"
	"strings"
	"time"

	"github.com/charmbracelet/lipgloss"
	"github.com/dustin/go-humanize"
	"lunchpail.io/pkg/lunchpail"
	"lunchpail.io/pkg/shrinkwrap/cpu"
	"lunchpail.io/pkg/views"
)

// Format `message` generated by some component `who`
func message(who, message string, style lipgloss.Style) string {
	return fmt.Sprintf("%s %s", style.Render(fmt.Sprintf("%8s", who)), views.Dim.Render(message))
}

type Resource string
const (
	Cpu Resource = "CPU"
	Mem = "Memory"
)

func cpuline(workers []cpu.Worker, resource Resource) string {
	line := []string{}

	prevPrefix := ""
	for _, worker := range workers {
		prefix := ""
		paddingLeft := 1
		switch worker.Component {
		case lunchpail.DispatcherComponent:
			prefix = "D "
		case lunchpail.WorkersComponent:
			prefix = "W "
		}

		if prefix == prevPrefix {
			prefix = ""
			paddingLeft = 0
		} else {
			prevPrefix = prefix
		}

		// compute the length of both cpu and mem, so we can align them across rows
		cpuVal := fmt.Sprintf("%s%s%%", prefix, humanize.FtoaWithDigits(worker.CpuUtil, 1))
		memVal := fmt.Sprintf("%s%s", prefix, humanize.Bytes(worker.MemoryBytes))
		maxlen := max(len(cpuVal), len(memVal))

		var val string
		switch resource {
		case Cpu:
			val = fmt.Sprintf("%-*s", maxlen, cpuVal)
		case Mem:
			val = fmt.Sprintf("%-*s", maxlen, memVal)
		}

		if val != "" {
			info := views.ComponentStyle(worker.Component).PaddingLeft(paddingLeft).Render(val)
			line = append(line, info)
		}
	}

	return message(string(resource), strings.Join(line, ""), views.OtherComponentStyle)
}

func footer(model Model, timestamp time.Time, maxheight int) []string {
	maxheight-- // minus one for this timestamp
	footer := []string{views.Dim.Render(timestamp.Format(time.RFC850))}

	if model.Cpu.HasData() {
		maxheight -= 2 // minus one for the cpu and memory line
		workers := model.Cpu.Sorted()
		footer = append(footer, cpuline(workers, Cpu))
		footer = append(footer, cpuline(workers, Mem))
	}

	// then use the rest of maxheight for messages
	for _, msg := range model.messages(maxheight) {
		footer = append(footer, message(msg.who, msg.message, views.DispatcherComponentStyle))
	}

	return footer
}
