{{- define "workdir/path" }}
workingDir: /workdir
{{- end }}

{{- define "workdir/volumeMount" }}
- name: workdir
  mountPath: /workdir
{{- if .Values.workdir.cm.data }}
- name: workdir-configmap
  mountPath: /workdir-code
{{- end }}
{{- end }}

{{- define "workdir/env" }}
- name: WORKDIR
  value: /workdir
{{- end }}

{{- define "workdir/volume" }}
- name: workdir
  emptyDir: {}
{{- if .Values.workdir.cm.data }}
- name: workdir-configmap
  projected:
    defaultMode: 0777
    sources:
      - configMap:
          name: {{ print (.Release.Name | trunc 44) "-workdir" }}
{{- end }}
{{- end }}

{{- if .Values.workdir.cm.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ print (.Release.Name | trunc 44) "-workdir" }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/managed-by: lunchpail.io
data:
{{- .Values.workdir.cm.data | b64dec | fromJson | toYaml | nindent 2 }}
{{- end }}
