{{- if .Values.lunchpail.ips.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lunchpail.ips.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.lunchpail.ips.dockerconfigjson }}
{{- end }}
