apiVersion: v1
kind: PersistentVolume
metadata:
  name: workdir
spec:
  capacity:
    storage: {{ .Values.workdir.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.workdir.clusterIP }}
    path: "/"
  mountOptions:
    - nfsvers=4.2
