{{- if eq .Values.workdir.fs "nfs" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nfs-server"
  namespace: {{ .Values.controllers.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/component: nfs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/component: nfs
    spec:
      terminationGracePeriodSeconds: 0
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        command: ["/bin/bash", "-c", "--"]
        args:
          - |
            mkdir /exports
            /usr/local/bin/run_nfs.sh /exports

        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME", "SYS_ADMIN", "CAP_DAC_READ_SEARCH"]
          privileged: true
{{- end }}
