apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workdir
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.workdir.size }}
  volumeName: workdir
