{{- if eq .Values.workdir.fs "nfs" }}
apiVersion: v1
kind: Service
metadata:
  name: workdir
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: {{ .Values.workdir.clusterIP }}
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
  - name: mountd
    port: 20048
    protocol: TCP
  - name: rpcbind
    port: 111
    protocol: UDP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: nfs
{{- end }}
