apiVersion: mcad.ibm.com/v1beta1
kind: AppWrapper
metadata:
  name: {{ print .Release.Name | trunc 53 }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: workerpool
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/managed-by: codeflare.dev
  ownerReferences:
    {{ include "owner" . | indent 4 }}
spec:
  resources:
    Items: []
    GenericItems:
      - replicas: 1
        generictemplate:
          {{ include "codeflare.dev/WorkerPool" . | indent 10 }}
