{{- if eq .Values.extract "config" }}
{{- if .Values.internalS3.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ print (.Release.Name | trunc 40) "-lunchpail-s3" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: s3
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: lunchpail.io
spec:
  ports:
  - name: api
    protocol: TCP
    port: {{ .Values.internalS3.port }}
    targetPort: 9000
  # - name: console
  #   protocol: TCP
  #   port: 9090
  #   targetPort: 9090
  selector:
    app.kubernetes.io/component: workstealer
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: lunchpail.io
{{- end }}
{{- end }}
