# Default values for MCAD-Controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deploymentName: mcad-controller
namespace: kube-system
replicaCount: 1
loglevel: 4

image:
  repository: darroyo/mcad-controller
  tag: quota-management-v1.29.40
  pullPolicy: IfNotPresent

crd:

httpImage:
  repository: restserver
  tag: latest
  pullPolicy: Always

httpServerImage:
  repository: httpserver
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 2000m
    memory: 2048Mi

imagePullSecret:
  name:
  username: iamapikey
  registry: registry.stage1.ng.bluemix.net
  password: dummyvalue

serviceAccount: mcad-controller

nodeSelector:
  hostname:

configMap:
  name: mcad-controller-configmap
  quotaEnabled: '"false"'
  multiCluster: false
  dispatcherMode: '"false"'
  preemptionEnabled: '"false"'
  agentConfigs: ""
  quotaRestUrl: ""
  # String timeout in milliseconds
  podCreationTimeout:

volumes:
  hostPath:

coscheduler:
  rbac:
    apiGroup: scheduling.sigs.k8s.io
    resource: podgroups

quotaManagement:
  rbac:
    apiGroup:
    resource:
