apiVersion: codeflare.dev/v1alpha1
kind: Application
metadata:
  name: hapq
  namespace: {{ .Values.namespace.preprocessing }}
spec:
  api: workqueue
  image: ghcr.io/lunchpail/ray22:0.2.0
#  repo: https://github.ibm.com/tmhoangt/foundation-model-stack/tree/RHODS_pipeline/src/llm/rhods/python/ods-automated-hap
  repo: https://github.ibm.com/cloud-computer/codeflare-platform/tree/main/watsonx_ai/charts/applications/templates/preprocessing/hapq
  command: /opt/codeflare/worker/bin/watcher.sh python -u hapq.py --models_folder=/mnt/datasets/hap-models
  supportsGpu: true
  description: >-
    Eliminate Hate and Profanity from a given input (a set of parquet
    files) using a given pre-trained model. This is the work queue
    implementation of HAP.
  inputs:
    - useas: mount
      sizes:
        xs: hap-models
