{{- if .Values.global.jaas.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.jaas.namespace.name }}
  labels:
    app.kubernetes.io/name: jaas
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    monitor-pods-datasets: enabled # datashim support for "dataset.0.id" pod labels -> volume/volumeMunt
{{- end }}
