apiVersion: v1
name: codeflare-tasksimulator
description: Deploys a workload that injects simulated tasks into a given queue
type: application

# Chart version.
version: 0.0.1

# CodeFlare version.
appVersion: "latest"
