{{- if and .Values.autorun .Values.autodispatcher .Values.autodispatcher.name .Values.autodispatcher.application }}
# Inject a WorkDispatcher if needed
apiVersion: codeflare.dev/v1alpha1
kind: WorkDispatcher
metadata:
  name: {{ .Values.autodispatcher.name }}
  namespace: {{ .Values.namespace.user }}
spec:
  run: {{ .Values.autorun }}
  method: application
  application:
    fromRole: dispatcher
{{- end }}
