# TODO run controller should create this on demand?
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.rbac.serviceaccount }}
  namespace: {{ .Release.Namespace }}

{{- if .Values.global.jaas.ips }}
imagePullSecrets:
  - name: {{ .Values.global.jaas.ips }}
{{- end }}
