{{- if eq .Values.extract "config" }}
{{- if .Values.internalS3.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ print (.Release.Name | trunc 40) "-lunchpail-minio" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: minio
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: lunchpail.io
data:
  S3_ENDPOINT: {{ print "http://" .Values.name ":9000" }}
  USE_MINIO_EXTENSIONS: "true"
{{- end }}
{{- end }}
