apiVersion: codeflare.dev/v1alpha1
kind: Application
metadata:
  name: example-lightning
  namespace: {{ .Values.namespace.examples }}
spec:
  api: torch
  image: ghcr.io/project-codeflare/lightning:0.0.6
  repo: https://github.ibm.com/ai-foundation/foundation-model-stack/tree/main/examples/src/ddp_example
  repoSecret:
    name: github-ibm-com-ai-foundation
    namespace: codeflare-ibm-internal
  command: python3 lightning_ddp_example.py
  size: sm
  supportsGpu: true
