apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: runs.codeflare.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: codeflare.dev
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                application:
                  type: string
                options:
                  type: string
                env:
                  type: object
                  additionalProperties:
                    type: string
                priority:
                  type: string
                  enum:
                    - low
                    - normal
                    - high
                size:
                  type: string
                  enum:
                    - xs
                    - sm
                    - md
                    - lg
                    - xl
                    - xxl
              required:
                - application
      additionalPrinterColumns:
        - name: Application
          type: string
          description: The application definition being run
          jsonPath: .spec.application
        - name: Options
          type: string
          description: Addition command line options
          jsonPath: .spec.options
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: runs
    # singular name to be used as an alias on the CLI and for display
    singular: run
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Run
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ru
