apiVersion: v1
kind: Service
metadata:
  name: {{ print (.Values.name | trunc 50) "-s3" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: s3
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: lunchpail.io
spec:
  ports:
  - name: api
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: 9000
  # - name: console
  #   protocol: TCP
  #   port: 9090
  #   targetPort: 9090
  selector:
    app.kubernetes.io/part-of: {{ .Values.appname }}
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/component: s3
