{{- define "containers/main" }}
- name: main
  image: {{ .Values.image }}
  command:
    {{- include "prestop/command" . | indent 4 }}

  env:
    - name: LUNCHPAIL_QUEUE_PATH
      value: {{ .Values.taskqueue.prefixPath }}
  {{- if .Values.env }}
    {{ .Values.env | b64dec | fromJsonArray | toYaml | nindent 4 }}
  {{- end }}

  {{- if .Values.containerSecurityContext }}
  securityContext: {{ .Values.containerSecurityContext | b64dec | fromYaml | toJson }}
  {{- end }}

  {{- if .Values.envFroms }}
  envFrom:
  {{ .Values.envFroms | b64dec | fromJsonArray | toYaml | nindent 2 }}
  {{- end }}

  {{- include "workdir/path" . | indent 2 }}
  volumeMounts:
    {{- if .Values.volumeMounts }}
    {{- .Values.volumeMounts | b64dec | fromJsonArray | toYaml | nindent 4 }}
    {{- end }}
    {{- include "workdir/volumeMount" . | indent 4 }}
  resources:
    limits:
      {{- if ne (.Values.workers.cpu | quote) "\"auto\"" }}
      cpu: {{ .Values.workers.cpu }}
      {{- end }}
      {{- if ne (.Values.workers.memory | quote) "\"auto\"" }}
      memory: {{ .Values.workers.memory }}
      {{- end }}
      {{- if and (.Values.workers.gpu) (gt .Values.workers.gpu 0) }}
      nvidia.com/gpu: {{ .Values.workers.gpu }}
      {{- end }}
    requests:
      {{- if ne (.Values.workers.cpu | quote) "\"auto\"" }}
      cpu: {{ .Values.workers.cpu }}
      {{- end }}
      {{- if ne (.Values.workers.memory | quote) "\"auto\"" }}
      memory: {{ .Values.workers.memory }}
      {{- end }}
      {{- if and (.Values.workers.gpu) (gt .Values.workers.gpu 0) }}
      nvidia.com/gpu: {{ .Values.workers.gpu }}
      {{- end }}

  readinessProbe:
    exec:
      command:
      - cat
      - /tmp/alive
    initialDelaySeconds: 1
    periodSeconds: 1

  {{- include "prestop/spec/container" . | indent 2 }}
{{- end }}
