{{- define "containers/main" }}
- name: main
  image: {{ .Values.image }}
  command: ["/bin/bash", "-c", {{ print "touch /tmp/alive && " .Values.command }}]
  env:
    - name: NAME
      value: {{ .Release.Name }}
    - name: NAMESPACE
      value: {{ .Values.namespace }}
    - name: ENCLOSING_UID
      value: {{ .Values.uid }}
    - name: ENCLOSING_RUN_NAME
      value: {{ .Values.name }}
    - name: RUN_NAME
      value: {{ .Values.name }}
    - name: WORKQUEUE
      value: /queue
    - name: S3_ENDPOINT_VAR
      value: {{ print .Values.queue.dataset "_endpoint" }}
    - name: AWS_ACCESS_KEY_ID_VAR
      value: {{ print .Values.queue.dataset "_accessKeyID" }}
    - name: AWS_SECRET_ACCESS_KEY_VAR
      value: {{ print .Values.queue.dataset "_secretAccessKey" }}
    - name: TASKQUEUE_VAR
      value: {{ print .Values.queue.dataset "_bucket" }}
    - name: LUNCHPAIL
      value: lunchpail
  {{- if .Values.containerSecurityContext }}
  securityContext: {{ .Values.containerSecurityContext | b64dec | fromYaml | toJson }}
  {{- end }}
      
  {{- if or .Values.env .Values.envFroms }}
  envFrom:
  {{- if .Values.env }}
  - configMapRef:
      name: {{ print .Release.Name | trunc 53 }}
  {{- end }}
  {{- if .Values.envFroms }}
  {{ .Values.envFroms | b64dec | fromJsonArray | toYaml | nindent 2 }}
  {{- end }}
  {{- end }}

  {{- include "workdir/path" . | indent 2 }}
  volumeMounts:
    {{- if .Values.volumeMounts }}
    {{- .Values.volumeMounts | b64dec | fromJsonArray | toYaml | nindent 4 }}
    {{- end }}
    {{- include "workdir/volumeMount" . | indent 4 }}
  resources:
    limits:
      {{- if ne (.Values.workers.cpu | quote) "\"auto\"" }}
      cpu: {{ .Values.workers.cpu }}
      {{- end }}
      {{- if ne (.Values.workers.memory | quote) "\"auto\"" }}
      memory: {{ .Values.workers.memory }}
      {{- end }}
      {{- if and (.Values.workers.gpu) (gt .Values.workers.gpu 0) }}
      nvidia.com/gpu: {{ .Values.workers.gpu }}
      {{- end }}
    requests:
      {{- if ne (.Values.workers.cpu | quote) "\"auto\"" }}
      cpu: {{ .Values.workers.cpu }}
      {{- end }}
      {{- if ne (.Values.workers.memory | quote) "\"auto\"" }}
      memory: {{ .Values.workers.memory }}
      {{- end }}
      {{- if and (.Values.workers.gpu) (gt .Values.workers.gpu 0) }}
      nvidia.com/gpu: {{ .Values.workers.gpu }}
      {{- end }}

  {{- if .Values.rbac.runAsRoot }}
  securityContext:
    privileged: true
  {{- end }}

  readinessProbe:
    exec:
      command:
      - cat
      - /tmp/alive
    initialDelaySeconds: 1
    periodSeconds: 1
{{- end }}
