{{- define "containers/workdir" }}
{{- if .Values.workdir.repo }}
- name: workdir
  image: {{ print .Values.lunchpail.image.registry "/" .Values.lunchpail.image.repo "/jaas-workdir-component:" .Values.lunchpail.image.version }}
  volumeMounts:
    {{ include "workdir/volumeMount" . | indent 4 }}
  env:
    {{ include "workdir/env" . | indent 4 }}
    - name: REPO
      value: {{ .Values.workdir.repo }}
  {{- if .Values.workdir.secretName }}
  envFrom:
    - secretRef:
        name: {{ print .Values.workdir.secretName }}
  {{- end }}
{{- end }}

{{- if .Values.workdir.cm.data }}
- name: workdir-code
  image: alpine:3
  volumeMounts:
    {{ include "workdir/volumeMount" . | indent 4 }}
  env:
    - name: LUNCHPAIL_SUBDIR
      value: {{ .Values.workdir.cm.mount_path | default "" }}
  command:
    - /bin/sh
    - "-c"
    - |
      mkdir -p /workdir/$LUNCHPAIL_SUBDIR
      cp -aH /workdir-code/* /workdir/$LUNCHPAIL_SUBDIR
      find /workdir
{{- end }}
{{- end }}
