{{- define "containers/workdir" }}
{{- if .Values.workdir.repo }}
- name: workdir
  image: {{ print .Values.lunchpail.image.registry "/" .Values.lunchpail.image.repo "/lunchpail-workdir:" .Values.lunchpail.image.version }}
  volumeMounts:
    {{ include "workdir/volumeMount" . | indent 4 }}
  env:
    {{ include "workdir/env" . | indent 4 }}
    - name: REPO
      value: {{ .Values.workdir.repo }}
  envFrom:
    {{ include "workdir/envFrom" . | indent 4 }}
{{- end }}

{{- if .Values.workdir.cm.data }}
- name: workdir-code
  image: docker.io/alpine:3
  volumeMounts:
    {{ include "workdir/volumeMount" . | indent 4 }}
  env:
    - name: LUNCHPAIL_SUBDIR
      value: {{ .Values.workdir.cm.mount_path | default "" }}
  command:
    - /bin/sh
    - "-c"
    - |
      mkdir -p /workdir/$LUNCHPAIL_SUBDIR
      cp -aH /workdir-code/* /workdir/$LUNCHPAIL_SUBDIR
      find /workdir
{{- end }}
{{- end }}
