{{- if .Values.taskqueue.auto }}
# the taskqueue to use, if none is provided by the application/command line
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.taskqueue.dataset }}
  labels:
    app.kubernetes.io/component: taskqueue
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  bucket: {{ .Values.taskqueue.dataset | b64enc }}
  endpoint: {{ .Values.taskqueue.endpoint | default .Values.global.s3Endpoint | b64enc }}
  accessKeyID: {{ .Values.taskqueue.accessKeyId | default .Values.global.s3AccessKey | b64enc }}
  secretAccessKey: {{ .Values.taskqueue.secretAccessKey | default .Values.global.s3SecretKey | b64enc }}
{{- end }}
