apiVersion: v1
kind: Secret
metadata:
  name: hap-secret
  namespace: {{ .Values.namespace.user }}
type: Opaque
data:
  accessKeyID: {{ .Values.cosAccessKey | b64enc }}
  secretAccessKey: {{ .Values.cosSecretKey | b64enc }}
