apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: quotasubtrees.ibm.com
  finalizers: []
spec:
  group: ibm.com
  scope: Namespaced
  names:
    kind: QuotaSubtree
    singular: quotasubtree
    plural: quotasubtrees
    shortNames:
    - qst
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          spec:
            type: object
            properties:    
              parent: 
                type: string
              parentNamespace:
                type: string
              children:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    quotas:
                      type: object
                      properties:
                        disabled: 
                          type: boolean
                        hardLimit: 
                          type: boolean
                        requests:
                          type: object
                          properties: 
                            cpu:
                              x-kubernetes-int-or-string: true
                              pattern: '^[0-9]*(m)?$'
                            memory:
                              x-kubernetes-int-or-string: true
                              pattern: '^[0-9]*(Ei|Pi|Ti|Gi|Mi|Ki|E|P|T|G|M|K)?$'
                            nvidia.com/gpu:
                              x-kubernetes-int-or-string: true
                              pattern: '^[0-9]?$'
