{{- define "containers/workstealer" }}
- name: workstealer
  image: {{ print .Values.image.registry "/" .Values.image.repo "/workstealer:" .Values.image.version }}
  command: ["/opt/lunchpail/workstealer/scripts/workstealer.sh"]
  volumeMounts:
    {{- include "scripts/volumeMount" . | indent 4 }}
  envFrom:
    - secretRef:
        name: {{ .Values.taskqueue.dataset }}
      prefix: {{ print .Values.taskqueue.dataset "_" }}
{{- if .Values.s3.enabled }}
    - secretRef:
        name: {{ print (.Release.Name | trunc 50) "-s3" }}
  ports:
    - containerPort: 9000
{{- end }}
  env:
{{- if .Values.s3.enabled }}
    - name: MINIO_ENABLED
      value: "yes"
{{- end }}
    - name: SLEEP_BEFORE_EXIT # if tests need to capture some output before we exit
      value: {{ .Values.lunchpail_internal.workstealer.sleep_before_exit | default 0 | quote }}
    - name: RUN_NAME
      value: {{ .Values.name }}
    - name: UNASSIGNED_INBOX
      value: {{ .Values.inbox | default "inbox" }}
    - name: FULLY_DONE_OUTBOX
      value: {{ .Values.outbox | default "outbox" }}
    - name: WORKER_QUEUES_SUBDIR
      value: queues
    - name: S3_ENDPOINT_VAR
      value: {{ print .Values.taskqueue.dataset "_endpoint" }}
    - name: AWS_ACCESS_KEY_ID_VAR
      value: {{ print .Values.taskqueue.dataset "_accessKeyID" }}
    - name: AWS_SECRET_ACCESS_KEY_VAR
      value: {{ print .Values.taskqueue.dataset "_secretAccessKey" }}
    - name: TASKQUEUE_VAR
      value: {{ print .Values.taskqueue.dataset "_bucket" }}
    - name: LUNCHPAIL
      value: {{ .Values.lunchpail }}
{{- end }}
