apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: runs.codeflare.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: codeflare.dev
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [application]
              properties:
                application:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                options:
                  type: string
                env:
                  type: object
                  additionalProperties:
                    type: string
                priority:
                  type: string
                  enum:
                    - low
                    - normal
                    - high
                workers:
                  type: number
                supportsGpu:
                  type: boolean
                size:
                  type: string
                  enum: [xxs,xs,sm,md,lg,xl,xxl]
                input:
                  type: string
                  enum: [xxs,xs,sm,md,lg,xl,xxl]
                inbox:
                  type: string
      # subresources for the custom resource
      subresources:
        # enables the status subresource
        status: {}
      additionalPrinterColumns:
        - name: Application
          type: string
          description: The application definition being run
          jsonPath: .spec.application.name
        #- name: Options
        #  type: string
        #  description: Addition command line options
        #  jsonPath: .spec.options
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Status
          type: string
          jsonPath: ".metadata.annotations.codeflare\\.dev/status"
        - name: Epoch
          type: string
          jsonPath: ".metadata.annotations.codeflare\\.dev/epoch"
        - name: Progress
          type: string
          jsonPath: ".metadata.annotations.codeflare\\.dev/epoch-progress"
        - name: Message
          type: string
          jsonPath: ".metadata.annotations.codeflare\\.dev/message"

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: runs
    # singular name to be used as an alias on the CLI and for display
    singular: run
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Run
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ru
