# TODO run controller should create this on demand?
apiVersion: v1
kind: Secret
metadata:
  name: workdir-jaas-secret
  namespace: {{ .Values.namespace.user }}
type: Opaque
data:
  accessKeyID: {{ .Values.global.s3AccessKey | b64enc }}
  secretAccessKey: {{ .Values.global.s3SecretKey | b64enc }}
