# Default values for MCAD-Controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deploymentName: mcad-controller
namespace: kube-system
replicaCount: 1
loglevel: 4

image:
  repository: quay.io/project-codeflare/mcad-controller
  tag: release-v1.32.0
  pullPolicy: IfNotPresent

crd:

httpImage:
  repository: restserver
  tag: latest
  pullPolicy: Always

httpServerImage:
  repository: httpserver
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 1
    memory: 1250Mi
#  requests:
#    cpu: 2000m
#    memory: 2048Mi

imagePullSecret:
  name:
  username: iamapikey
  registry: registry.stage1.ng.bluemix.net
  password: dummyvalue

serviceAccount: mcad-controller

nodeSelector:
  hostname:

configMap:
  name:
  quotaEnabled: '"false"'
  multiCluster: false
  dispatcherMode: '"false"'
  preemptionEnabled: '"false"'
  agentConfigs: ""
  quotaRestUrl: ""
  # String timeout in milliseconds
  podCreationTimeout:

volumes:
  hostPath:

coscheduler:
  rbac:
    apiGroup: scheduling.x-k8s.io
    resource: podgroups

kuberay:
  rbac:
    apiGroup: ray.io
    resource: rayjobs

spark:
  rbac:
    apiGroup: sparkoperator.k8s.io
    resource: sparkapplications
    
quotaManagement:
  rbac:
    apiGroup:
    resource:
