apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: codeflare.dev
      app.kubernetes.io/name: {{ .Values.name }}
      app.kubernetes.io/component: s3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: codeflare.dev
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/component: s3
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
        - name: data
          hostPath:
          emptyDir:
            sizeLimit: {{ .Values.emptyDir.sizeLimit }}
        
      containers:
      - name: minio
        image: {{ .Values.images.server }}
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: {{ .Values.name }}
        command:
          - /bin/bash
          - -c
        args: 
          - "echo 'Cleaning /data' && find /data | wc -l && rm -rf /data/* && rm -rf /data/.minio.sys && find /data && find /data | wc -l && echo 'Starting minio' && MINIO_ROOT_USER=$AWS_ACCESS_KEY_ID MINIO_ROOT_PASSWORD=$AWS_SECRET_ACCESS_KEY minio server /data --console-address :9090"
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          requests:
            memory: 1Gi
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9090
          hostPort: 9090
        # Mount the volume into the pod
        volumeMounts:
        - name: data # must match the volume name, above
          mountPath: "/data"

        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 15
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
