apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: codeflare.dev
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: s3
spec:
  ports:
  - name: api
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: console
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/part-of: codeflare.dev
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: s3
