apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: images.codeflare.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: codeflare.dev
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [image]
              properties:
                image:
                  type: string
      # subresources for the custom resource
      subresources:
        # enables the status subresource
        status: {}
      additionalPrinterColumns:
        - name: Image
          type: string
          description: The image path
          jsonPath: .spec.image
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: images
    # singular name to be used as an alias on the CLI and for display
    singular: image
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Image
    # shortNames allow shorter string to match your resource on the CLI
    #shortNames:
    #- im
