{{ if .never }}
apiVersion: codeflare.dev/v1alpha1
kind: Application
metadata:
  name: queue-example
  namespace: {{ .Values.namespace.user }}
  labels:
    app.kubernetes.io/component: examples
    app.kubernetes.io/part-of: codeflare.dev
spec:
  api: workqueue
  image: {{ print .Values.image.registry "/" .Values.image.repo "/jaas-workerpool-worker-alpine-component:" .Values.image.version }}
  command: /opt/lunchpail/worker/bin/watcher.sh ./main.sh
  code: |
    #!/usr/bin/env sh

    # $1 filepath
    # $2 processing folder
    # $3 outbox folder
    in="$1"
    processing="$2"
    out="$3"

    echo "Processing $in"
    mv $in $processing

    sleep 5

    echo "Done with $processing"
    mv $processing $out

  description: A simple example of a workqueue-style application.
  inputs:
    - sizes:
        lg: queueexample
{{ end }}
