{{ if .never }}
apiVersion: v1
kind: Secret
metadata:
  name: queue-example-cfsecret # avoid dashes for now: https://github.com/datashim-io/datashim/issues/285
  namespace: {{ .Values.namespace.user }}
  labels:
    app.kubernetes.io/component: examples
    app.kubernetes.io/part-of: codeflare.dev
type: Opaque
data:
  accessKeyID: {{ .Values.global.s3AccessKey | b64enc }}
  secretAccessKey: {{ .Values.global.s3SecretKey | b64enc }}
{{ end }}
