{{ if .never }}
apiVersion: {{ .Values.datashim.apiVersion }}
kind: Dataset
metadata:
  name: queueexample # avoid dashes for now: https://github.com/datashim-io/datashim/issues/285
  namespace: {{ .Values.namespace.user }}
  labels:
    app.kubernetes.io/component: taskqueue
    app.kubernetes.io/part-of: codeflare.dev
spec:
  local:
    type: "COS"
    bucket: queue-example
    endpoint: {{ .Values.global.s3Endpoint }}
    secret-name: queue-example-cfsecret
    secret-namespace: {{ .Values.namespace.user }}
    #readonly: "true" # default is false
    provision: "true"
{{ end }}
