apiVersion: v1
name: codeflare-watsonx-ai
description: Deploys IBM WatsonX AI extensions to CodeFlare platform
type: application

# Chart version.
version: 0.0.1

# CodeFlare version.
appVersion: "latest"
