name: CI Tests

# cancel any prior runs for this workflow and this PR (or branch)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        SCRIPT:
          - ./tests/bin/ci.sh -e 'test(7.*|8.*)' # baseline tests
          - ./tests/bin/ci.sh -i 'test7.*' -e 'test8.*' # including only test7* tests (simpler tests)
          - ./tests/bin/ci.sh -i 'test8.*' -e 'test7.*' # including only test8* tests (application tests)
          - ./tests/bin/go.sh
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.10.0
      with:
        install_only: true

    - name: Setup
      run: ./tests/bin/travis/setup.sh

    - name: Check Docker
      run: docker version && podman version

    - name: Run Test with args ${{ matrix.ARGS }}
      env:
        TERM: xterm-256color
      run: bash -c "${{matrix.SCRIPT}} ${{matrix.ARGS }}"
