name: Kind

# cancel any prior runs for this workflow and this PR (or branch)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kind:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        profile:
          - run-controller.sh
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.7.0
      with:
        install_only: true

    #- name: Setup
    #  env:
    #    TERM: xterm
    #  run: ./tests/kind/setup-ci.sh

    - name: Run Test with profile ${{ matrix.profile }}
      env:
        EXECUTABLE_PATH: github-actions-production
        DEBUG_KUBERNETES: true
      run: ./tests/kind/${{ matrix.profile }}
