name: CI Tests

# cancel any prior runs for this workflow and this PR (or branch)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        LUNCHPAIL_TARGET:
          - kubernetes
          - local
        SCRIPT:
          - ./tests/bin/ci.sh -e 'test(7.*|8.*)|python.*' # baseline tests
          - ./tests/bin/ci.sh -i 'test7.*' -e 'test7(b.*|c.*|d.*|e.*|f.*|g.*|h.*)'
          - ./tests/bin/ci.sh -i 'test7(b.*|c.*|d.*|e.*|g.*|h.*)' 
          - ./tests/bin/ci.sh -i 'test7f.*'
          - ./tests/bin/ci.sh -i 'test8.*'
          - ./tests/bin/ci.sh -i 'python-code.*'
          - ./tests/bin/ci.sh -i 'python-language.*'
          - ./tests/bin/ci.sh -i 'python-universal.*'
          - ./tests/bin/go.sh
          - ./tests/bin/pipelines.sh
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    # we will also be testing installing kind, so we don't want to do
    # this as part of the github action workflow
    #- name: Create k8s Kind Cluster
    #  uses: helm/kind-action@v1.10.0
    #  with:
    #    install_only: true

    - name: Check Docker
      run: docker version && podman version

    - name: Run Test with args ${{ matrix.ARGS }}
      env:
        TERM: xterm-256color
        LUNCHPAIL_TARGET: ${{ matrix.LUNCHPAIL_TARGET }}
      run: bash -c "${{matrix.SCRIPT}} ${{matrix.ARGS }}"
