FROM ghcr.io/project-codeflare/kopf:0.0.3

RUN addgroup -g 2000 jaas && adduser -u 2000 jaas -G jaas --disabled-password && echo "jaas:jaas" | chpasswd
USER jaas

ADD src /src
CMD kopf run /src/handlers.py --verbose
