# secrets needed to access the queue
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lunchpail.taskqueue.dataset }}
  labels:
    app.kubernetes.io/component: taskqueue
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  bucket: {{ .Values.lunchpail.taskqueue.bucket }}
  endpoint: {{ .Values.lunchpail.taskqueue.endpoint }}
  accessKeyID: {{ .Values.lunchpail.taskqueue.accessKey }}
  secretAccessKey: {{ .Values.lunchpail.taskqueue.secretKey }}
  queuePrefixPath: {{ .Values.lunchpail.taskqueue.prefixPath }}
