{{- if .Values.lunchpail.runAsJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ print .Release.Name }}
  labels:
    app.kubernetes.io/component: {{ .Values.lunchpail.component }}
    app.kubernetes.io/part-of: {{ .Values.lunchpail.partOf }}
    app.kubernetes.io/name: {{ .Values.lunchpail.instanceName }}
    app.kubernetes.io/instance: {{ .Values.lunchpail.name }}
    app.kubernetes.io/managed-by: lunchpail.io
spec:
  completionMode: Indexed
  parallelism: {{ .Values.workers.count }}
  completions: 99999999
  # ttlSecondsAfterFinished: 10000
  backoffLimit: 6
  template:
    metadata:
      {{- include "pod/labels" . | indent 6}}
    {{- include "pod/spec" . | indent 4}}
{{- end }}
