{{- define "prestop/spec/pod" }}
{{- if eq .Values.component "workdispatcher" }}
terminationGracePeriodSeconds: 5 # give time for the preStop in the container
{{- end }}
{{- end }}

{{- define "prestop/spec/container" }}
{{- if eq .Values.component "workdispatcher" }}
lifecycle:
  preStop:
    exec:
      command: ["lunchpail", "qdone"]
{{- end }}
{{- end }}

{{- define "prestop/command" }}
{{- if eq .Values.component "workdispatcher" }}
- /bin/sh
- "-c"
- |
  touch /tmp/alive && {{ .Values.command }}
  lunchpail qdone
  echo "INFO Done with my part of the job"
{{- else }}
- /bin/sh
- "-c"
- |
  touch /tmp/alive && {{ .Values.command }}
{{- end }}
{{- end }}
