{{- define "prestop/spec/pod" }}
{{- if eq .Values.lunchpail.component "workdispatcher" }}
terminationGracePeriodSeconds: 5 # give time for the preStop in the container
{{- end }}
{{- end }}

{{- define "prestop/spec/container" }}
{{- if eq .Values.lunchpail.component "workdispatcher" }}
lifecycle:
  preStop:
    exec:
      command: ["lunchpail", "qdone"]
{{- end }}
{{- end }}
