{{- if .Values.lunchpail.secrets }}
{{- range $i, $secret := .Values.lunchpail.secrets }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ print $.Values.lunchpail.secretPrefix $i }}
stringData:
{{ $secret | b64dec | fromJson | toYaml | indent 2 }}
{{- end }}
{{- end }}
